# Netlify Configuration for Portfolio

[build]
  publish = "."

[[edge_functions]]
  function = "curl-handler"
  path = "/*"

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.pdf"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Disposition = "inline"

# Redirects (optional)
[[redirects]]
  from = "/resume"
  to = "/Mohammed-Muteeullah-Resume.pdf"
  status = 302

[[redirects]]
  from = "/github"
  to = "https://github.com/mmuteeullah"
  status = 302

[[redirects]]
  from = "/linkedin"
  to = "https://linkedin.com/in/muteeullah"
  status = 302
